name: llm_guided_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py39h06a4308_0
  - aiohttp=3.11.10=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py39h06a4308_0
  - anyio=4.7.0=py39h06a4308_0
  - arrow-cpp=19.0.0=h865e1df_1
  - async-timeout=5.0.1=py39h06a4308_0
  - attrs=24.3.0=py39h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py39h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - datasets=3.3.2=py39h06a4308_0
  - dill=0.3.8=py39h06a4308_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - filelock=3.17.0=py39h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py39h5eee18b_0
  - fsspec=2024.12.0=py39h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - h11=0.14.0=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.1.0=py39h5eee18b_0
  - multiprocess=0.70.15=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.2.1=py39h06a4308_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.2=py39h06a4308_0
  - pandas=2.2.3=py39h6a678d5_0
  - pillow=11.1.0=py39hac6e08b_1
  - pip=25.0=py39h06a4308_0
  - propcache=0.3.1=py39h5eee18b_0
  - protobuf=4.25.3=py39he36ed58_1
  - pyarrow=19.0.0=py39h6a678d5_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py39h5eee18b_0
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py39h5eee18b_0
  - requests=2.32.3=py39h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py39h922eef2_0
  - setuptools=75.8.0=py39h06a4308_0
  - six=1.17.0=py39h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py39ha92566c_0
  - tqdm=4.67.1=py39h2f386ee_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py39h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.45.1=py39h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py39h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.6.0
      - antlr4-python3-runtime==4.9.3
      - deap==1.4.2
      - einops==0.8.1
      - fastapi==0.115.12
      - flash-attn==2.7.4.post1
      - huggingface-hub==0.30.2
      - hydra-core==1.2.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - psutil==7.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - starlette==0.46.2
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0
      - transformers==4.51.3
      - triton==3.2.0
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
prefix: /home/hice1/dnguyen448/.conda/envs/llm_guided_env
